language: php

php:
  - 7.1
  - 7.2
  - nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --dev
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - mkdir -p build/logs
  - phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - travis_retry php vendor/bin/coveralls -v
